x = float(input("Enter first number :"))
y = float(input("Enter second Number :"))
print("sum is =",x + y)
print("Sub is =",x - y)
print("div is =",x / y)
print("multi is =",x * y)
print("Mod is =",x % y)